source 'https://rubygems.org'
# ruby '1.9.3'

gem 'activerecord'
gem 'faker'
gem 'json'
gem 'newrelic_rpm'
gem 'pg'
gem 'pry'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'redis'
gem 'rspec'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'typhoeus'
gem 'unicorn'
# gem 'puma'
# gem 'pry-byebug'

gem 'sinatra-assetpack', :require => 'sinatra/assetpack'